config:
  info: master branch,springcloud-config/config-dev.yml version=7
eureka:
  client:
    service-url:
      defaultZone: http://cloud.eureka.server1.com:7001/eureka/,http://cloud.eureka.server2.com:7002/eureka/,http://cloud.eureka.server3.com:7003/eureka/
